name: Notify Telegram on PR Close

on:
  pull_request:
    types:
      - closed

jobs:
  notify-telegram:
    uses: SIC-TLU/sic-actions/.github/workflows/notify-telegram.yml@main
    with:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_TOPIC_ID }}
