name: Notify Telegram on PR Close
on:
  pull_request:
    types:
      - closed

jobs:
  notify-telegram:
    uses: SIC-TLU/sic-actions/.github/workflows/notify-telegram.yml@main
    secrets: inherit
